version: "3.8"

services:
  api:
    build:
      context: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:dbsekret@db
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: dbsekret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432

volumes:
  postgres-data:
